openapi: '3.0.2'
info:
  title: NFT watcher
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /auth/signup:
    post:
      description: 'Sign up'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                publicAddress:
                  type: string
                password:
                  type: string
        required: true
      responses:
        '201':
          description: 'User successfuly Signed up'
        '409':
          description: 'email or publicAddress already registered'
